#!/bin/bash
if [ "$1" == "debug" ]; then
  echo "#### DEBUG MODE ACTIVATED ####"
  sass -r sass-globbing --watch assets/sass:assets/css -t expanded
else
  sass -r sass-globbing --watch assets/sass:assets/css -t compressed
fi
